// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://csvennedhvhugoeixjjf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNzdmVubmVkaHZodWdvZWl4ampmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NDIwOTgsImV4cCI6MjA2NDQxODA5OH0.w_lEPb9y8GFQzRcIB_vwM9ZPAXrxJAbP5OwEUmWEgVQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);